# PrintPing Configuration File
# You can edit these settings. The application will use them on next launch.

ping_interval_seconds: 3
port_check_timeout_seconds: 1
default_ports_to_check:
- 21
- 80
- 161
- 443
browser_preferences:
- name: Google Chrome
  exec:
    Windows: chrome
    Linux: google-chrome
    Darwin: Google Chrome
  args:
  - --ignore-certificate-errors
  - --test-type
- name: Microsoft Edge
  exec:
    Windows: msedge
    Linux: microsoft-edge
    Darwin: Microsoft Edge
  args:
  - --ignore-certificate-errors
- name: Mozilla Firefox
  exec:
    Windows: firefox
    Linux: firefox
    Darwin: Firefox
  args: []
